services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\GlobalContentBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaGlobalContentBundle.php'
